spring:
  config:
    activate:
      on-profile: test
  # h2 db의 인메모리 db 기능을 활용하여
  # 별도의 db를 설치 혹은 실행하지 않고도 db 테스트 가능
  datasource:
    driver-class-name: org.h2.Driver
    #    url: jdbc:h2:mem:test
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:

  jpa:
    database: h2
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        globally_quoted_identifiers: true
        format_sql: true
        default_batch_fetch_size: 100

logging.level:
  org.hibernate.SQL: debug

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace